### PR TITLE
fix game history to standard notation

### LINKED ISSUE #27: Game history standard notation
The game history must look like this:
image

move number, white move, black move

You can use this symbols for it:
♔ ♕ ♖ ♗ ♘
♚ ♛ ♜ ♝ ♞

### PR DESCRIPTION
**Pull request by dzianisshupenka**
Now you can enjoy game history with standard notation

### CODE REVIEW

**Review by juggler39 — APPROVED** [review]

**Comment by juggler39** [comment]
Looks good

File: frontend/src/components/Aiboard.vue [hunk 1]
```diff
@@ -46,12 +46,14 @@ export default {
...
-        };
-        this.updateHistory(move);
+        if (this.game.history().length % 2 === 0) {
+          let move = [
+            this.game
+              .history({ verbose: true })
+              .slice(this.game.history().length - 2, this.game.history().length)
+          ];
+          this.updateHistory(move);
+        }
```
Comment (juggler39) [inline frontend/src/components/Aiboard.vue:56]: Move this code into GameHistory component to avoid duplications. Or create a function and put it in the parent chessboard component.
